fixed notifications to chat, sending with postJsonAsync
kanboard/plugin-rocketchat pull request #9
Opened 2018-02-28 14:48 UTC by fchyla

fix for issue #8

2018-03-05 18:51 UTC, fguillot requested changes

2018-03-05 18:51 UTC, fguillot commented on Notification/RocketChat.php
> +#           'icon_url' => 'https://kanboard.net/assets/img/favicon.png',
Why do you commit commented code?

2018-03-07 10:22 UTC, fchyla commented
@fguillot commented code removed

2018-03-08 22:22 UTC, fguillot requested changes
The unit tests need to be updated as well. The build is broken.

2018-03-08 22:22 UTC, fguillot commented on Notification/RocketChat.php
> +
you don't need to commit whitespaces :)

2018-03-16 20:32 UTC, fguillot commented
Are you going to fix the unit tests as well? Let me know if you don't know how to it.

2018-03-19 09:11 UTC, fchyla commented
I do not know how to do that. If you could help that would be great.

2018-03-23 15:16 UTC, fchyla commented
If I understand correctly Test/RocketChatTest.php has to be rewritten to work with the new JSON message format. I do not have enough knowledge to do it help will be appreciated.

2018-03-30 16:54 UTC, fguillot commented
PR merged manually.

2018-03-30 16:54 UTC, closed without merging